Add support for GitHub App token
AlmaLinux/albs-github-integration pull request #5
Opened 2024-04-11 21:14 UTC by maccelf

Resolves: AlmaLinux/build-system#239

2024-04-23 10:41 UTC, Korulag approved these changes

2024-04-24 14:38 UTC, anfimovdm requested changes

2024-04-24 14:38 UTC, anfimovdm commented on albs_github/graphql/client.py
> +            },
please, add `raise_for_status=True` and check on the web server side that we get token

2024-05-14 13:15 UTC, soksanichenko requested changes

2024-05-14 13:15 UTC, soksanichenko commented on albs_github/graphql/client.py
> +            'exp': int(time.time()) + 600,
Move a number to constant var

2024-05-14 13:27 UTC, soksanichenko approved these changes

2024-05-14 21:31 UTC, anfimovdm approved these changes

2024-05-15 22:41 UTC, javihernandez approved these changes

2024-05-16 09:10 UTC, merged